#!/usr/bin/env python3
from __future__ import annotations
import json,os,platform,shutil,subprocess
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parent; OUT=ROOT/".libertas"
def run(*args):
 try:
  p=subprocess.run(args,cwd=ROOT,text=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=False)
  return p.stdout.strip() if p.returncode==0 else ""
 except FileNotFoundError: return ""
def load(name):
 p=ROOT/name
 if not p.is_file(): raise SystemExit(f"LIBERTAS BOOT: FAIL missing {name}")
 try: return json.loads(p.read_text(encoding="utf-8"))
 except Exception as e: raise SystemExit(f"LIBERTAS BOOT: FAIL invalid {name}: {e}")
for rel in ["SOUL.md","AGENTS.md","SYSTEM_CONTRACT.json","CAPABILITY_REGISTRY.json","MODULE_REGISTRY.json","DEVELOPMENT_STATE.json"]:
 if not (ROOT/rel).is_file(): raise SystemExit(f"LIBERTAS BOOT: FAIL missing {rel}")
contract=load("SYSTEM_CONTRACT.json"); caps=load("CAPABILITY_REGISTRY.json"); mods=load("MODULE_REGISTRY.json"); state=load("DEVELOPMENT_STATE.json")
branch=run("git","branch","--show-current") or os.environ.get("GITHUB_REF_NAME","unknown"); sha=run("git","rev-parse","HEAD") or os.environ.get("GITHUB_SHA","unknown"); dirty=bool(run("git","status","--porcelain"))
runtime={"schema":"libertas.runtime-capabilities.v1","platform":platform.platform(),"python":platform.python_version(),"node":run("node","--version") or None,"npm":run("npm","--version") or None,"git":run("git","--version") or None,"github_actions":os.environ.get("GITHUB_ACTIONS")=="true","commands":{k:bool(shutil.which(k)) for k in ["git","node","npm","cargo","rustc"]}}
module_ids={m.get("id") for m in mods.get("modules",[])}
if state.get("active_module") not in module_ids: raise SystemExit("LIBERTAS BOOT: FAIL active module is not registered")
OUT.mkdir(exist_ok=True)
session={"schema":"libertas.session.v1","created_at":datetime.now(timezone.utc).isoformat(),"branch":branch,"sha":sha,"dirty":dirty,"active_module":state.get("active_module"),"phase":state.get("phase"),"github_actions":runtime["github_actions"]}
(OUT/"session.json").write_text(json.dumps(session,indent=2)+"\n",encoding="utf-8"); (OUT/"runtime_capabilities.json").write_text(json.dumps(runtime,indent=2)+"\n",encoding="utf-8")
active=next(m for m in mods["modules"] if m["id"]==state["active_module"])
brain=f"""# Libertas0 Session Second Brain

Generated by `bootstrap.py`. Repository contracts remain authority.

- Branch: `{branch}`
- SHA: `{sha}`
- Working tree dirty at boot: `{dirty}`
- Phase: `{state.get('phase')}`
- Active module: `{state.get('active_module')}`
- Module state: `{active.get('state')}`
- Current objective: {state.get('current_objective')}
- Last passing gate: {state.get('last_passing_gate')}
- Product code authorized: `{state.get('product_code_authorized')}`

## Exact next action
{state.get('exact_next_action')}

## Development law
- Human instruction is highest authority.
- Only the active module is in scope unless explicitly changed.
- GitHub issue #1 + `validation/local-debug` is the local debug bridge.
- Realtime musical authority must remain deterministic.
- Tests do not imply physical proof unless the required gate says so.

## Runtime snapshot
- Platform: {runtime['platform']}
- Python: {runtime['python']}
- Node: {runtime['node']}
- GitHub Actions: {runtime['github_actions']}
"""
(OUT/"SECOND_BRAIN.md").write_text(brain,encoding="utf-8")
print("LIBERTAS BOOT: PASS"); print(f"branch={branch}"); print(f"sha={sha}"); print(f"active_module={state.get('active_module')}"); print(f"next={state.get('exact_next_action')}")
